# Generated by Django 5.2 on 2025-07-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_room_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=30)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomwords",
                        to="game.room",
                    ),
                ),
            ],
            options={"unique_together": {("room", "text")},},
        ),
    ]
