# Generated by Django 5.2.4 on 2025-07-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
